version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2013
configuration: Release
platform: Any CPU
clone_folder: c:\project\FontAwesome
assembly_info:
  patch: true
  file: '\src\FontAwesome\Properties\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build:
  project: src\FontAwesome\FontAwesome.csproj
  publish_nuget: true
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: BN1qIm8VoXCZjw+wjEuF2CUxl0C/tp+dI2Iu398n7V6yyza5sJcO2egiUHQQ8Y4fIgXVoumdc5Em+LTNf+ex3i+CbCLyHWl4mppmaZif4xo=
  on:
    APPVEYOR_REPO_TAG: true